-- MySQL Script generated by MySQL Workbench
-- Fri 29 Nov 2024 10:04:56 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cargo_reso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cargo_reso` (
  `cd_cargo_reso` INT NOT NULL AUTO_INCREMENT,
  `nm_cargo_reso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_cargo_reso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `cd_usuario` VARCHAR(10) NOT NULL,
  `nm_usuario` VARCHAR(50) NOT NULL,
  `nm_email` VARCHAR(50) NOT NULL,
  `cd_senha` VARCHAR(255) NOT NULL,
  `dt_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `st_ativo` TINYINT NOT NULL DEFAULT 1,
  `verificado` CHAR(1) NOT NULL DEFAULT '0',
  `dt_exclusao` DATETIME NULL,
  `nm_real` VARCHAR(45) NULL,
  `nr_telefone` VARCHAR(45) NULL,
  `dt_nascimento` DATE NULL,
  `id_cargo_reso` INT NOT NULL,
  `url_imagem_perfil` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`cd_usuario`),
  UNIQUE INDEX `nm_usuario_UNIQUE` (`nm_usuario` ASC) VISIBLE,
  UNIQUE INDEX `nm_email_UNIQUE` (`nm_email` ASC) VISIBLE,
  INDEX `fk_tb_usuario_tb_cargo_reso1_idx` (`id_cargo_reso` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_tb_cargo_reso1`
    FOREIGN KEY (`id_cargo_reso`)
    REFERENCES `mydb`.`tb_cargo_reso` (`cd_cargo_reso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_unidade` (
  `cd_unidade` INT NOT NULL AUTO_INCREMENT,
  `nm_unidade` VARCHAR(50) NOT NULL,
  `codigo_unidade` VARCHAR(255) NOT NULL,
  `dt_unidade` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `st_ativo` TINYINT NOT NULL DEFAULT 1,
  `dt_exclusao` DATETIME NULL,
  PRIMARY KEY (`cd_unidade`),
  UNIQUE INDEX `codigo_unidade_UNIQUE` (`codigo_unidade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cargo_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cargo_unidade` (
  `cd_cargo` INT NOT NULL AUTO_INCREMENT,
  `nm_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario_unidade` (
  `id_usuario` VARCHAR(10) NOT NULL,
  `id_unidade` INT NOT NULL,
  `dt_entrada` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_cargo` INT NOT NULL,
  `st_ativo` TINYINT NOT NULL DEFAULT 1,
  `dt_exclusao` DATETIME NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_unidade`),
  INDEX `fk_tb_usuario_has_tb_unidade_tb_unidade1_idx` (`id_unidade` ASC) VISIBLE,
  INDEX `fk_tb_usuario_has_tb_unidade_tb_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_tb_usuario_unidade_tb_cargo_unidade1_idx` (`id_cargo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_has_tb_unidade_tb_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_has_tb_unidade_tb_unidade1`
    FOREIGN KEY (`id_unidade`)
    REFERENCES `mydb`.`tb_unidade` (`cd_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_unidade_tb_cargo_unidade1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `mydb`.`tb_cargo_unidade` (`cd_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_st_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_st_sala` (
  `cd_sala` INT NOT NULL AUTO_INCREMENT,
  `nm_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_sala` (
  `cd_sala` INT NOT NULL AUTO_INCREMENT,
  `nm_sala` VARCHAR(45) NOT NULL,
  `ds_sala` VARCHAR(255) NOT NULL,
  `dt_sala` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_usuario` VARCHAR(10) NOT NULL,
  `id_unidade` INT NOT NULL,
  `st_ativo` TINYINT NOT NULL DEFAULT 1,
  `dt_exclusao` DATETIME NULL,
  `st_sala` INT NOT NULL,
  PRIMARY KEY (`cd_sala`),
  INDEX `fk_tb_sala_tb_usuario_unidade1_idx` (`id_usuario` ASC, `id_unidade` ASC) VISIBLE,
  INDEX `fk_tb_sala_tb_st_sala1_idx` (`st_sala` ASC) VISIBLE,
  CONSTRAINT `fk_tb_sala_tb_usuario_unidade1`
    FOREIGN KEY (`id_usuario` , `id_unidade`)
    REFERENCES `mydb`.`tb_usuario_unidade` (`id_usuario` , `id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_sala_tb_st_sala1`
    FOREIGN KEY (`st_sala`)
    REFERENCES `mydb`.`tb_st_sala` (`cd_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_equipamento_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_equipamento_categoria` (
  `cd_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria_nm` VARCHAR(45) NOT NULL,
  `id_usuario` VARCHAR(10) NOT NULL,
  `id_unidade` INT NOT NULL,
  `st_ativo` TINYINT NOT NULL DEFAULT 1,
  `dt_exclusao` DATETIME NULL,
  `dt_categoria` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cd_categoria`),
  INDEX `fk_tb_equipamento_categoria_tb_usuario_unidade1_idx` (`id_usuario` ASC, `id_unidade` ASC) VISIBLE,
  CONSTRAINT `fk_tb_equipamento_categoria_tb_usuario_unidade1`
    FOREIGN KEY (`id_usuario` , `id_unidade`)
    REFERENCES `mydb`.`tb_usuario_unidade` (`id_usuario` , `id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_st_equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_st_equipamento` (
  `cd_st_equipamento` INT NOT NULL AUTO_INCREMENT,
  `nm_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_st_equipamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_equipamento` (
  `cd_equipamento` INT NOT NULL AUTO_INCREMENT,
  `nm_equipamento` VARCHAR(45) NOT NULL,
  `ds_equipamento` LONGTEXT NOT NULL,
  `dt_equipamento` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `st_equipamento` INT NOT NULL,
  `id_categoria` INT NULL,
  `id_usuario` VARCHAR(10) NOT NULL,
  `id_unidade` INT NOT NULL,
  `id_sala` INT NOT NULL,
  `st_ativo` TINYINT NOT NULL DEFAULT 1,
  `dt_exclusao` DATETIME NULL,
  PRIMARY KEY (`cd_equipamento`),
  INDEX `fk_tb_equipamento_tb_st_equipamento1_idx` (`st_equipamento` ASC) VISIBLE,
  INDEX `fk_tb_equipamento_tb_equipamento_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_tb_equipamento_tb_usuario_unidade1_idx` (`id_usuario` ASC, `id_unidade` ASC) VISIBLE,
  INDEX `fk_tb_equipamento_tb_sala1_idx` (`id_sala` ASC) VISIBLE,
  CONSTRAINT `fk_tb_equipamento_tb_st_equipamento1`
    FOREIGN KEY (`st_equipamento`)
    REFERENCES `mydb`.`tb_st_equipamento` (`cd_st_equipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_equipamento_tb_equipamento_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`tb_equipamento_categoria` (`cd_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_equipamento_tb_usuario_unidade1`
    FOREIGN KEY (`id_usuario` , `id_unidade`)
    REFERENCES `mydb`.`tb_usuario_unidade` (`id_usuario` , `id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_equipamento_tb_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `mydb`.`tb_sala` (`cd_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_st_chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_st_chamado` (
  `cd_st_chamado` INT NOT NULL AUTO_INCREMENT,
  `nm_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_st_chamado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_chamado` (
  `cd_chamado` INT NOT NULL AUTO_INCREMENT,
  `nm_chamado` VARCHAR(45) NOT NULL,
  `ds_chamado` LONGTEXT NOT NULL,
  `ds_recado` LONGTEXT NULL,
  `dt_abertura` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_fechamento` DATETIME NULL,
  `nr_avaliacao` CHAR(5) NULL,
  `st_chamado` INT NOT NULL,
  `id_usuario_abertura` VARCHAR(10) NOT NULL,
  `id_unidade` INT NOT NULL,
  `id_usuario_fechamento` VARCHAR(10) NULL,
  `id_equipamento` INT NULL,
  `st_ativo` TINYINT NOT NULL DEFAULT 1,
  `dt_exclusao` DATETIME NULL,
  PRIMARY KEY (`cd_chamado`),
  INDEX `fk_tb_chamado_tb_st_chamado1_idx` (`st_chamado` ASC) VISIBLE,
  INDEX `fk_tb_chamado_tb_usuario_unidade1_idx` (`id_usuario_abertura` ASC, `id_unidade` ASC) VISIBLE,
  INDEX `fk_tb_chamado_tb_usuario_unidade2_idx` (`id_usuario_fechamento` ASC) VISIBLE,
  INDEX `fk_tb_chamado_tb_equipamento1_idx` (`id_equipamento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_chamado_tb_st_chamado1`
    FOREIGN KEY (`st_chamado`)
    REFERENCES `mydb`.`tb_st_chamado` (`cd_st_chamado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_chamado_tb_usuario_unidade1`
    FOREIGN KEY (`id_usuario_abertura` , `id_unidade`)
    REFERENCES `mydb`.`tb_usuario_unidade` (`id_usuario` , `id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_chamado_tb_usuario_unidade2`
    FOREIGN KEY (`id_usuario_fechamento`)
    REFERENCES `mydb`.`tb_usuario_unidade` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_chamado_tb_equipamento1`
    FOREIGN KEY (`id_equipamento`)
    REFERENCES `mydb`.`tb_equipamento` (`cd_equipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_categoria_faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_categoria_faq` (
  `cd_categoria_faq` INT NOT NULL AUTO_INCREMENT,
  `nm_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_categoria_faq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_faq` (
  `cd_faq` INT NOT NULL AUTO_INCREMENT,
  `nm_pergunta` VARCHAR(45) NOT NULL,
  `nm_resposta` LONGTEXT NOT NULL,
  `dt_cadastro_faq` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_categoria` INT NOT NULL,
  `id_usuario` VARCHAR(10) NOT NULL,
  `st_ativo` TINYINT NOT NULL,
  `dt_exclusao` DATETIME NULL,
  PRIMARY KEY (`cd_faq`),
  INDEX `fk_tb_faq_tb_categoria_faq1_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_tb_faq_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_faq_tb_categoria_faq1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`tb_categoria_faq` (`cd_categoria_faq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_faq_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_chat` (
  `cd_mensagem` INT NOT NULL AUTO_INCREMENT,
  `mensagem` LONGTEXT NOT NULL,
  `dt_envio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_chamado` INT NOT NULL,
  `id_usuario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cd_mensagem`),
  INDEX `fk_tb_chat_tb_chamado1_idx` (`id_chamado` ASC) VISIBLE,
  INDEX `fk_tb_chat_tb_usuario_unidade1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_chat_tb_chamado1`
    FOREIGN KEY (`id_chamado`)
    REFERENCES `mydb`.`tb_chamado` (`cd_chamado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_chat_tb_usuario_unidade1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`tb_usuario_unidade` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
